# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ws01_response_ou import WS01ResponseOU  # noqa: F401,E501
from swagger_server import util


class WS01ResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ou: List[WS01ResponseOU]=None, cod_amm: str=None, des_amm: str=None):  # noqa: E501
        """WS01ResponseData - a model defined in Swagger

        :param ou: The ou of this WS01ResponseData.  # noqa: E501
        :type ou: List[WS01ResponseOU]
        :param cod_amm: The cod_amm of this WS01ResponseData.  # noqa: E501
        :type cod_amm: str
        :param des_amm: The des_amm of this WS01ResponseData.  # noqa: E501
        :type des_amm: str
        """
        self.swagger_types = {
            'ou': List[WS01ResponseOU],
            'cod_amm': str,
            'des_amm': str
        }

        self.attribute_map = {
            'ou': 'OU',
            'cod_amm': 'cod_amm',
            'des_amm': 'des_amm'
        }

        self._ou = ou
        self._cod_amm = cod_amm
        self._des_amm = des_amm

    @classmethod
    def from_dict(cls, dikt) -> 'WS01ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WS01Response_data of this WS01ResponseData.  # noqa: E501
        :rtype: WS01ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ou(self) -> List[WS01ResponseOU]:
        """Gets the ou of this WS01ResponseData.


        :return: The ou of this WS01ResponseData.
        :rtype: List[WS01ResponseOU]
        """
        return self._ou

    @ou.setter
    def ou(self, ou: List[WS01ResponseOU]):
        """Sets the ou of this WS01ResponseData.


        :param ou: The ou of this WS01ResponseData.
        :type ou: List[WS01ResponseOU]
        """

        self._ou = ou

    @property
    def cod_amm(self) -> str:
        """Gets the cod_amm of this WS01ResponseData.

        Codice Ente accreditato in IPA  # noqa: E501

        :return: The cod_amm of this WS01ResponseData.
        :rtype: str
        """
        return self._cod_amm

    @cod_amm.setter
    def cod_amm(self, cod_amm: str):
        """Sets the cod_amm of this WS01ResponseData.

        Codice Ente accreditato in IPA  # noqa: E501

        :param cod_amm: The cod_amm of this WS01ResponseData.
        :type cod_amm: str
        """

        self._cod_amm = cod_amm

    @property
    def des_amm(self) -> str:
        """Gets the des_amm of this WS01ResponseData.

        Denominazione Ente accreditato in IPA  # noqa: E501

        :return: The des_amm of this WS01ResponseData.
        :rtype: str
        """
        return self._des_amm

    @des_amm.setter
    def des_amm(self, des_amm: str):
        """Sets the des_amm of this WS01ResponseData.

        Denominazione Ente accreditato in IPA  # noqa: E501

        :param des_amm: The des_amm of this WS01ResponseData.
        :type des_amm: str
        """

        self._des_amm = des_amm
