# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WS01ResponseOU(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cod_uni_ou: str=None, des_ou: str=None, stato_canale: str=None):  # noqa: E501
        """WS01ResponseOU - a model defined in Swagger

        :param cod_uni_ou: The cod_uni_ou of this WS01ResponseOU.  # noqa: E501
        :type cod_uni_ou: str
        :param des_ou: The des_ou of this WS01ResponseOU.  # noqa: E501
        :type des_ou: str
        :param stato_canale: The stato_canale of this WS01ResponseOU.  # noqa: E501
        :type stato_canale: str
        """
        self.swagger_types = {
            'cod_uni_ou': str,
            'des_ou': str,
            'stato_canale': str
        }

        self.attribute_map = {
            'cod_uni_ou': 'cod_uni_ou',
            'des_ou': 'des_ou',
            'stato_canale': 'stato_canale'
        }

        self._cod_uni_ou = cod_uni_ou
        self._des_ou = des_ou
        self._stato_canale = stato_canale

    @classmethod
    def from_dict(cls, dikt) -> 'WS01ResponseOU':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WS01Response_OU of this WS01ResponseOU.  # noqa: E501
        :rtype: WS01ResponseOU
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cod_uni_ou(self) -> str:
        """Gets the cod_uni_ou of this WS01ResponseOU.

        Codice Univoco Ufficio destinatario di Fatturazione Elettroniche  # noqa: E501

        :return: The cod_uni_ou of this WS01ResponseOU.
        :rtype: str
        """
        return self._cod_uni_ou

    @cod_uni_ou.setter
    def cod_uni_ou(self, cod_uni_ou: str):
        """Sets the cod_uni_ou of this WS01ResponseOU.

        Codice Univoco Ufficio destinatario di Fatturazione Elettroniche  # noqa: E501

        :param cod_uni_ou: The cod_uni_ou of this WS01ResponseOU.
        :type cod_uni_ou: str
        """

        self._cod_uni_ou = cod_uni_ou

    @property
    def des_ou(self) -> str:
        """Gets the des_ou of this WS01ResponseOU.

        Denominazione Unita Organizzativa  # noqa: E501

        :return: The des_ou of this WS01ResponseOU.
        :rtype: str
        """
        return self._des_ou

    @des_ou.setter
    def des_ou(self, des_ou: str):
        """Sets the des_ou of this WS01ResponseOU.

        Denominazione Unita Organizzativa  # noqa: E501

        :param des_ou: The des_ou of this WS01ResponseOU.
        :type des_ou: str
        """

        self._des_ou = des_ou

    @property
    def stato_canale(self) -> str:
        """Gets the stato_canale of this WS01ResponseOU.

        A: Canale Attivo, V: In Fase di validazione  # noqa: E501

        :return: The stato_canale of this WS01ResponseOU.
        :rtype: str
        """
        return self._stato_canale

    @stato_canale.setter
    def stato_canale(self, stato_canale: str):
        """Sets the stato_canale of this WS01ResponseOU.

        A: Canale Attivo, V: In Fase di validazione  # noqa: E501

        :param stato_canale: The stato_canale of this WS01ResponseOU.
        :type stato_canale: str
        """

        self._stato_canale = stato_canale
