# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WS02ResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cap: str=None, cod_amm: str=None, cod_aoo: str=None, cogn_resp: str=None, comune: str=None, des_aoo: str=None, fax: str=None, indirizzo: str=None, mail1: str=None, mail2: str=None, mail3: str=None, mail_resp: str=None, nome_resp: str=None, provincia: str=None, regione: str=None, tel: str=None, tel_resp: str=None):  # noqa: E501
        """WS02ResponseData - a model defined in Swagger

        :param cap: The cap of this WS02ResponseData.  # noqa: E501
        :type cap: str
        :param cod_amm: The cod_amm of this WS02ResponseData.  # noqa: E501
        :type cod_amm: str
        :param cod_aoo: The cod_aoo of this WS02ResponseData.  # noqa: E501
        :type cod_aoo: str
        :param cogn_resp: The cogn_resp of this WS02ResponseData.  # noqa: E501
        :type cogn_resp: str
        :param comune: The comune of this WS02ResponseData.  # noqa: E501
        :type comune: str
        :param des_aoo: The des_aoo of this WS02ResponseData.  # noqa: E501
        :type des_aoo: str
        :param fax: The fax of this WS02ResponseData.  # noqa: E501
        :type fax: str
        :param indirizzo: The indirizzo of this WS02ResponseData.  # noqa: E501
        :type indirizzo: str
        :param mail1: The mail1 of this WS02ResponseData.  # noqa: E501
        :type mail1: str
        :param mail2: The mail2 of this WS02ResponseData.  # noqa: E501
        :type mail2: str
        :param mail3: The mail3 of this WS02ResponseData.  # noqa: E501
        :type mail3: str
        :param mail_resp: The mail_resp of this WS02ResponseData.  # noqa: E501
        :type mail_resp: str
        :param nome_resp: The nome_resp of this WS02ResponseData.  # noqa: E501
        :type nome_resp: str
        :param provincia: The provincia of this WS02ResponseData.  # noqa: E501
        :type provincia: str
        :param regione: The regione of this WS02ResponseData.  # noqa: E501
        :type regione: str
        :param tel: The tel of this WS02ResponseData.  # noqa: E501
        :type tel: str
        :param tel_resp: The tel_resp of this WS02ResponseData.  # noqa: E501
        :type tel_resp: str
        """
        self.swagger_types = {
            'cap': str,
            'cod_amm': str,
            'cod_aoo': str,
            'cogn_resp': str,
            'comune': str,
            'des_aoo': str,
            'fax': str,
            'indirizzo': str,
            'mail1': str,
            'mail2': str,
            'mail3': str,
            'mail_resp': str,
            'nome_resp': str,
            'provincia': str,
            'regione': str,
            'tel': str,
            'tel_resp': str
        }

        self.attribute_map = {
            'cap': 'cap',
            'cod_amm': 'cod_amm',
            'cod_aoo': 'cod_aoo',
            'cogn_resp': 'cogn_resp',
            'comune': 'comune',
            'des_aoo': 'des_aoo',
            'fax': 'fax',
            'indirizzo': 'indirizzo',
            'mail1': 'mail1',
            'mail2': 'mail2',
            'mail3': 'mail3',
            'mail_resp': 'mail_resp',
            'nome_resp': 'nome_resp',
            'provincia': 'provincia',
            'regione': 'regione',
            'tel': 'tel',
            'tel_resp': 'tel_resp'
        }

        self._cap = cap
        self._cod_amm = cod_amm
        self._cod_aoo = cod_aoo
        self._cogn_resp = cogn_resp
        self._comune = comune
        self._des_aoo = des_aoo
        self._fax = fax
        self._indirizzo = indirizzo
        self._mail1 = mail1
        self._mail2 = mail2
        self._mail3 = mail3
        self._mail_resp = mail_resp
        self._nome_resp = nome_resp
        self._provincia = provincia
        self._regione = regione
        self._tel = tel
        self._tel_resp = tel_resp

    @classmethod
    def from_dict(cls, dikt) -> 'WS02ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WS02Response_data of this WS02ResponseData.  # noqa: E501
        :rtype: WS02ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cap(self) -> str:
        """Gets the cap of this WS02ResponseData.

        Cap registrato in IPA per la sede dell'AOO  # noqa: E501

        :return: The cap of this WS02ResponseData.
        :rtype: str
        """
        return self._cap

    @cap.setter
    def cap(self, cap: str):
        """Sets the cap of this WS02ResponseData.

        Cap registrato in IPA per la sede dell'AOO  # noqa: E501

        :param cap: The cap of this WS02ResponseData.
        :type cap: str
        """

        self._cap = cap

    @property
    def cod_amm(self) -> str:
        """Gets the cod_amm of this WS02ResponseData.

        Codice Ente accreditato in IPA  # noqa: E501

        :return: The cod_amm of this WS02ResponseData.
        :rtype: str
        """
        return self._cod_amm

    @cod_amm.setter
    def cod_amm(self, cod_amm: str):
        """Sets the cod_amm of this WS02ResponseData.

        Codice Ente accreditato in IPA  # noqa: E501

        :param cod_amm: The cod_amm of this WS02ResponseData.
        :type cod_amm: str
        """

        self._cod_amm = cod_amm

    @property
    def cod_aoo(self) -> str:
        """Gets the cod_aoo of this WS02ResponseData.

        Codice AOO  # noqa: E501

        :return: The cod_aoo of this WS02ResponseData.
        :rtype: str
        """
        return self._cod_aoo

    @cod_aoo.setter
    def cod_aoo(self, cod_aoo: str):
        """Sets the cod_aoo of this WS02ResponseData.

        Codice AOO  # noqa: E501

        :param cod_aoo: The cod_aoo of this WS02ResponseData.
        :type cod_aoo: str
        """

        self._cod_aoo = cod_aoo

    @property
    def cogn_resp(self) -> str:
        """Gets the cogn_resp of this WS02ResponseData.

        Cognome del responsabile dell'AOO  # noqa: E501

        :return: The cogn_resp of this WS02ResponseData.
        :rtype: str
        """
        return self._cogn_resp

    @cogn_resp.setter
    def cogn_resp(self, cogn_resp: str):
        """Sets the cogn_resp of this WS02ResponseData.

        Cognome del responsabile dell'AOO  # noqa: E501

        :param cogn_resp: The cogn_resp of this WS02ResponseData.
        :type cogn_resp: str
        """

        self._cogn_resp = cogn_resp

    @property
    def comune(self) -> str:
        """Gets the comune of this WS02ResponseData.

        Comune registrato in IPA per la sede dell'AOO  # noqa: E501

        :return: The comune of this WS02ResponseData.
        :rtype: str
        """
        return self._comune

    @comune.setter
    def comune(self, comune: str):
        """Sets the comune of this WS02ResponseData.

        Comune registrato in IPA per la sede dell'AOO  # noqa: E501

        :param comune: The comune of this WS02ResponseData.
        :type comune: str
        """

        self._comune = comune

    @property
    def des_aoo(self) -> str:
        """Gets the des_aoo of this WS02ResponseData.

        Nome dell'AOO  # noqa: E501

        :return: The des_aoo of this WS02ResponseData.
        :rtype: str
        """
        return self._des_aoo

    @des_aoo.setter
    def des_aoo(self, des_aoo: str):
        """Sets the des_aoo of this WS02ResponseData.

        Nome dell'AOO  # noqa: E501

        :param des_aoo: The des_aoo of this WS02ResponseData.
        :type des_aoo: str
        """

        self._des_aoo = des_aoo

    @property
    def fax(self) -> str:
        """Gets the fax of this WS02ResponseData.

        Numero di fax registrato in IPA per dell’AOO  # noqa: E501

        :return: The fax of this WS02ResponseData.
        :rtype: str
        """
        return self._fax

    @fax.setter
    def fax(self, fax: str):
        """Sets the fax of this WS02ResponseData.

        Numero di fax registrato in IPA per dell’AOO  # noqa: E501

        :param fax: The fax of this WS02ResponseData.
        :type fax: str
        """

        self._fax = fax

    @property
    def indirizzo(self) -> str:
        """Gets the indirizzo of this WS02ResponseData.

        Indirizzo postale registrato in IPA per la sede dell'AOO  # noqa: E501

        :return: The indirizzo of this WS02ResponseData.
        :rtype: str
        """
        return self._indirizzo

    @indirizzo.setter
    def indirizzo(self, indirizzo: str):
        """Sets the indirizzo of this WS02ResponseData.

        Indirizzo postale registrato in IPA per la sede dell'AOO  # noqa: E501

        :param indirizzo: The indirizzo of this WS02ResponseData.
        :type indirizzo: str
        """

        self._indirizzo = indirizzo

    @property
    def mail1(self) -> str:
        """Gets the mail1 of this WS02ResponseData.

        Indirizzo email primario associato all’AOO  # noqa: E501

        :return: The mail1 of this WS02ResponseData.
        :rtype: str
        """
        return self._mail1

    @mail1.setter
    def mail1(self, mail1: str):
        """Sets the mail1 of this WS02ResponseData.

        Indirizzo email primario associato all’AOO  # noqa: E501

        :param mail1: The mail1 of this WS02ResponseData.
        :type mail1: str
        """

        self._mail1 = mail1

    @property
    def mail2(self) -> str:
        """Gets the mail2 of this WS02ResponseData.

        Indirizzo email associato all’AOO  # noqa: E501

        :return: The mail2 of this WS02ResponseData.
        :rtype: str
        """
        return self._mail2

    @mail2.setter
    def mail2(self, mail2: str):
        """Sets the mail2 of this WS02ResponseData.

        Indirizzo email associato all’AOO  # noqa: E501

        :param mail2: The mail2 of this WS02ResponseData.
        :type mail2: str
        """

        self._mail2 = mail2

    @property
    def mail3(self) -> str:
        """Gets the mail3 of this WS02ResponseData.

        Indirizzo email associato all’AOO  # noqa: E501

        :return: The mail3 of this WS02ResponseData.
        :rtype: str
        """
        return self._mail3

    @mail3.setter
    def mail3(self, mail3: str):
        """Sets the mail3 of this WS02ResponseData.

        Indirizzo email associato all’AOO  # noqa: E501

        :param mail3: The mail3 of this WS02ResponseData.
        :type mail3: str
        """

        self._mail3 = mail3

    @property
    def mail_resp(self) -> str:
        """Gets the mail_resp of this WS02ResponseData.

        Indirizzo email del responsabile dell'AOO  # noqa: E501

        :return: The mail_resp of this WS02ResponseData.
        :rtype: str
        """
        return self._mail_resp

    @mail_resp.setter
    def mail_resp(self, mail_resp: str):
        """Sets the mail_resp of this WS02ResponseData.

        Indirizzo email del responsabile dell'AOO  # noqa: E501

        :param mail_resp: The mail_resp of this WS02ResponseData.
        :type mail_resp: str
        """

        self._mail_resp = mail_resp

    @property
    def nome_resp(self) -> str:
        """Gets the nome_resp of this WS02ResponseData.

        Nome del responsabile dell'AOO  # noqa: E501

        :return: The nome_resp of this WS02ResponseData.
        :rtype: str
        """
        return self._nome_resp

    @nome_resp.setter
    def nome_resp(self, nome_resp: str):
        """Sets the nome_resp of this WS02ResponseData.

        Nome del responsabile dell'AOO  # noqa: E501

        :param nome_resp: The nome_resp of this WS02ResponseData.
        :type nome_resp: str
        """

        self._nome_resp = nome_resp

    @property
    def provincia(self) -> str:
        """Gets the provincia of this WS02ResponseData.

        Provincia registrata in IPA per la sede dell'AOO  # noqa: E501

        :return: The provincia of this WS02ResponseData.
        :rtype: str
        """
        return self._provincia

    @provincia.setter
    def provincia(self, provincia: str):
        """Sets the provincia of this WS02ResponseData.

        Provincia registrata in IPA per la sede dell'AOO  # noqa: E501

        :param provincia: The provincia of this WS02ResponseData.
        :type provincia: str
        """

        self._provincia = provincia

    @property
    def regione(self) -> str:
        """Gets the regione of this WS02ResponseData.

        Regione registrata in IPA per la sede dell'AOO  # noqa: E501

        :return: The regione of this WS02ResponseData.
        :rtype: str
        """
        return self._regione

    @regione.setter
    def regione(self, regione: str):
        """Sets the regione of this WS02ResponseData.

        Regione registrata in IPA per la sede dell'AOO  # noqa: E501

        :param regione: The regione of this WS02ResponseData.
        :type regione: str
        """

        self._regione = regione

    @property
    def tel(self) -> str:
        """Gets the tel of this WS02ResponseData.

        Numero di telefono registrato in IPA per dell’AOO  # noqa: E501

        :return: The tel of this WS02ResponseData.
        :rtype: str
        """
        return self._tel

    @tel.setter
    def tel(self, tel: str):
        """Sets the tel of this WS02ResponseData.

        Numero di telefono registrato in IPA per dell’AOO  # noqa: E501

        :param tel: The tel of this WS02ResponseData.
        :type tel: str
        """

        self._tel = tel

    @property
    def tel_resp(self) -> str:
        """Gets the tel_resp of this WS02ResponseData.

        Numero di telefono del responsabile dell'AOO  # noqa: E501

        :return: The tel_resp of this WS02ResponseData.
        :rtype: str
        """
        return self._tel_resp

    @tel_resp.setter
    def tel_resp(self, tel_resp: str):
        """Sets the tel_resp of this WS02ResponseData.

        Numero di telefono del responsabile dell'AOO  # noqa: E501

        :param tel_resp: The tel_resp of this WS02ResponseData.
        :type tel_resp: str
        """

        self._tel_resp = tel_resp
