# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WS04ResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cf: str=None, cod_amm: str=None, cod_aoo: str=None, cod_uni_ou: str=None, dat_val_canale_trasm_sfe: str=None, des_ou: str=None, dt_verifca_cf: str=None, stato_canale: str=None):  # noqa: E501
        """WS04ResponseData - a model defined in Swagger

        :param cf: The cf of this WS04ResponseData.  # noqa: E501
        :type cf: str
        :param cod_amm: The cod_amm of this WS04ResponseData.  # noqa: E501
        :type cod_amm: str
        :param cod_aoo: The cod_aoo of this WS04ResponseData.  # noqa: E501
        :type cod_aoo: str
        :param cod_uni_ou: The cod_uni_ou of this WS04ResponseData.  # noqa: E501
        :type cod_uni_ou: str
        :param dat_val_canale_trasm_sfe: The dat_val_canale_trasm_sfe of this WS04ResponseData.  # noqa: E501
        :type dat_val_canale_trasm_sfe: str
        :param des_ou: The des_ou of this WS04ResponseData.  # noqa: E501
        :type des_ou: str
        :param dt_verifca_cf: The dt_verifca_cf of this WS04ResponseData.  # noqa: E501
        :type dt_verifca_cf: str
        :param stato_canale: The stato_canale of this WS04ResponseData.  # noqa: E501
        :type stato_canale: str
        """
        self.swagger_types = {
            'cf': str,
            'cod_amm': str,
            'cod_aoo': str,
            'cod_uni_ou': str,
            'dat_val_canale_trasm_sfe': str,
            'des_ou': str,
            'dt_verifca_cf': str,
            'stato_canale': str
        }

        self.attribute_map = {
            'cf': 'cf',
            'cod_amm': 'cod_amm',
            'cod_aoo': 'cod_aoo',
            'cod_uni_ou': 'cod_uni_ou',
            'dat_val_canale_trasm_sfe': 'dat_val_canale_trasm_sfe',
            'des_ou': 'des_ou',
            'dt_verifca_cf': 'dt_verifca_cf',
            'stato_canale': 'stato_canale'
        }

        self._cf = cf
        self._cod_amm = cod_amm
        self._cod_aoo = cod_aoo
        self._cod_uni_ou = cod_uni_ou
        self._dat_val_canale_trasm_sfe = dat_val_canale_trasm_sfe
        self._des_ou = des_ou
        self._dt_verifca_cf = dt_verifca_cf
        self._stato_canale = stato_canale

    @classmethod
    def from_dict(cls, dikt) -> 'WS04ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WS04Response_data of this WS04ResponseData.  # noqa: E501
        :rtype: WS04ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cf(self) -> str:
        """Gets the cf of this WS04ResponseData.

        Codice fiscale del servizio di fatturazione elettronica  # noqa: E501

        :return: The cf of this WS04ResponseData.
        :rtype: str
        """
        return self._cf

    @cf.setter
    def cf(self, cf: str):
        """Sets the cf of this WS04ResponseData.

        Codice fiscale del servizio di fatturazione elettronica  # noqa: E501

        :param cf: The cf of this WS04ResponseData.
        :type cf: str
        """

        self._cf = cf

    @property
    def cod_amm(self) -> str:
        """Gets the cod_amm of this WS04ResponseData.

        Codice Ente accreditato in IPA  # noqa: E501

        :return: The cod_amm of this WS04ResponseData.
        :rtype: str
        """
        return self._cod_amm

    @cod_amm.setter
    def cod_amm(self, cod_amm: str):
        """Sets the cod_amm of this WS04ResponseData.

        Codice Ente accreditato in IPA  # noqa: E501

        :param cod_amm: The cod_amm of this WS04ResponseData.
        :type cod_amm: str
        """

        self._cod_amm = cod_amm

    @property
    def cod_aoo(self) -> str:
        """Gets the cod_aoo of this WS04ResponseData.

        Codice AOO  # noqa: E501

        :return: The cod_aoo of this WS04ResponseData.
        :rtype: str
        """
        return self._cod_aoo

    @cod_aoo.setter
    def cod_aoo(self, cod_aoo: str):
        """Sets the cod_aoo of this WS04ResponseData.

        Codice AOO  # noqa: E501

        :param cod_aoo: The cod_aoo of this WS04ResponseData.
        :type cod_aoo: str
        """

        self._cod_aoo = cod_aoo

    @property
    def cod_uni_ou(self) -> str:
        """Gets the cod_uni_ou of this WS04ResponseData.

        Codice Univoco dell'Ufficio di fatturazione elettronica  # noqa: E501

        :return: The cod_uni_ou of this WS04ResponseData.
        :rtype: str
        """
        return self._cod_uni_ou

    @cod_uni_ou.setter
    def cod_uni_ou(self, cod_uni_ou: str):
        """Sets the cod_uni_ou of this WS04ResponseData.

        Codice Univoco dell'Ufficio di fatturazione elettronica  # noqa: E501

        :param cod_uni_ou: The cod_uni_ou of this WS04ResponseData.
        :type cod_uni_ou: str
        """

        self._cod_uni_ou = cod_uni_ou

    @property
    def dat_val_canale_trasm_sfe(self) -> str:
        """Gets the dat_val_canale_trasm_sfe of this WS04ResponseData.

        Data di inizio validità del servizio di fatturazione  # noqa: E501

        :return: The dat_val_canale_trasm_sfe of this WS04ResponseData.
        :rtype: str
        """
        return self._dat_val_canale_trasm_sfe

    @dat_val_canale_trasm_sfe.setter
    def dat_val_canale_trasm_sfe(self, dat_val_canale_trasm_sfe: str):
        """Sets the dat_val_canale_trasm_sfe of this WS04ResponseData.

        Data di inizio validità del servizio di fatturazione  # noqa: E501

        :param dat_val_canale_trasm_sfe: The dat_val_canale_trasm_sfe of this WS04ResponseData.
        :type dat_val_canale_trasm_sfe: str
        """

        self._dat_val_canale_trasm_sfe = dat_val_canale_trasm_sfe

    @property
    def des_ou(self) -> str:
        """Gets the des_ou of this WS04ResponseData.

        Nome dell'UO  # noqa: E501

        :return: The des_ou of this WS04ResponseData.
        :rtype: str
        """
        return self._des_ou

    @des_ou.setter
    def des_ou(self, des_ou: str):
        """Sets the des_ou of this WS04ResponseData.

        Nome dell'UO  # noqa: E501

        :param des_ou: The des_ou of this WS04ResponseData.
        :type des_ou: str
        """

        self._des_ou = des_ou

    @property
    def dt_verifca_cf(self) -> str:
        """Gets the dt_verifca_cf of this WS04ResponseData.

        Data di validazione del cf  # noqa: E501

        :return: The dt_verifca_cf of this WS04ResponseData.
        :rtype: str
        """
        return self._dt_verifca_cf

    @dt_verifca_cf.setter
    def dt_verifca_cf(self, dt_verifca_cf: str):
        """Sets the dt_verifca_cf of this WS04ResponseData.

        Data di validazione del cf  # noqa: E501

        :param dt_verifca_cf: The dt_verifca_cf of this WS04ResponseData.
        :type dt_verifca_cf: str
        """

        self._dt_verifca_cf = dt_verifca_cf

    @property
    def stato_canale(self) -> str:
        """Gets the stato_canale of this WS04ResponseData.

        Stato del canale di fatturazione  # noqa: E501

        :return: The stato_canale of this WS04ResponseData.
        :rtype: str
        """
        return self._stato_canale

    @stato_canale.setter
    def stato_canale(self, stato_canale: str):
        """Sets the stato_canale of this WS04ResponseData.

        Stato del canale di fatturazione  # noqa: E501

        :param stato_canale: The stato_canale of this WS04ResponseData.
        :type stato_canale: str
        """

        self._stato_canale = stato_canale
